# Generated by Django 3.2.18 on 2023-06-09 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20230601_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostmanFunctionality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postman_functionality_name', models.CharField(max_length=400, verbose_name='Nombre de funcionalidad')),
            ],
            options={
                'verbose_name_plural': 'Postman - Funcionalidad',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type_name', models.CharField(max_length=300, verbose_name='Tipo de video')),
            ],
            options={
                'verbose_name_plural': 'Videos - Tipos de videos',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('link', models.URLField(help_text="Se debe ir al video de Youtube y hacer click derecho sobre el video, y copiar el link 'Copiar URL del vídeo'", verbose_name='Youtube Link')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='documentation.videotype')),
            ],
            options={
                'verbose_name_plural': 'Videos - Videos',
            },
        ),
        migrations.CreateModel(
            name='Postman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=300, verbose_name='Nombre de colección')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('version_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero de version')),
                ('visible', models.BooleanField(default=True)),
                ('postman_file', models.FileField(upload_to='', verbose_name='Colección Postman')),
                ('functionality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='documentation.postmanfunctionality')),
            ],
            options={
                'verbose_name_plural': 'Postman - Archivos',
            },
        ),
    ]
