# Generated by Django 4.2.6 on 2023-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0013_showfilters_dual_checkbox_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showfilters',
            name='dual_checkbox_field',
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='sp_http_oracle_filter',
            field=models.BooleanField(default=True, help_text='Marque esta casilla para habilitar el filtro SP HTTP SQL.', verbose_name='Filtro SP HTTP SQL'),
        ),
    ]
