# Generated by Django 4.2.6 on 2023-11-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0014_remove_showfilters_dual_checkbox_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='showfilters',
            name='videos_filter',
            field=models.BooleanField(default=True, verbose_name='Videos'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='config_filter',
            field=models.BooleanField(default=True, verbose_name='Configuraciones'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='db_filter',
            field=models.BooleanField(default=True, verbose_name='Base de Datos'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='docs_filter',
            field=models.BooleanField(default=True, verbose_name='Documentos'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='postman_filter',
            field=models.BooleanField(default=True, verbose_name='Postman'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='sp_http_oracle_filter',
            field=models.BooleanField(default=True, verbose_name='SP HTTP Oracle'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='sp_http_sql_filter',
            field=models.BooleanField(default=True, verbose_name='SP HTTP SQL server'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='type_filter',
            field=models.BooleanField(default=False, help_text='Marque esta casilla para activar el filtro', verbose_name='Mostrar Filtro'),
        ),
        migrations.AlterField(
            model_name='showfilters',
            name='version_filter',
            field=models.BooleanField(default=True, verbose_name='Versiones'),
        ),
    ]
