# Generated by Django 4.2.6 on 2023-11-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0008_showfilters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showfilters',
            options={'verbose_name_plural': 'Filtros de Menu'},
        ),
    ]
