# Generated by Django 4.2.6 on 2023-11-02 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0009_alter_showfilters_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showfilters',
            options={'verbose_name_plural': 'Filtros - Menu'},
        ),
    ]
