# Generated by Django 4.2.6 on 2023-11-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0010_alter_showfilters_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='showfilters',
            name='name_filter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre del Filtro'),
        ),
        migrations.AddField(
            model_name='showfilters',
            name='type_filter',
            field=models.BooleanField(default=False),
        ),
    ]
