# Generated by Django 4.2.6 on 2023-11-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0012_alter_showfilters_type_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='showfilters',
            name='dual_checkbox_field',
            field=models.BooleanField(default=False),
        ),
    ]
